### ISSUE TITLE
建议可以把PushNotification放在changeIP里

### ISSUE THREAD

**Issue by Shouyupedia** [acacia233/Project-WARP-Unlock#1]
function Test_Netflix_Access {
    local result1="$(curl --interface $Interface --user-agent "${UA_Browser}" -fsL --write-out %{http_code} --output /dev/null --max-time 5 "https://www.netflix.com/title/81215567" 2>&1)"
    local result2="$(curl --interface $Interface --user-agent "${UA_Browser}" -fs --max-time 10 --write-out %{redirect_url} --output /dev/null "https://www.netflix.com/title/80018499" | cut -d '/' -f4 | cut -d '-' -f1 2>&1)"
    if [[ "$result1" != "200" ]] && [[ "$result2" != "$Region" ]]; 
    then
        ChangeIP
    fi
}

function ChangeIP {
    wg-quick down $Interface >/dev/null 2>&1
    sleep 2
    wg-quick up $Interface >/dev/null 2>&1
    let Count++
    Test_Netflix_Access
    PushNotification
}

原本每次运行脚本都往tg推一次消息（

**Comment by acacia233** [comment]
1.运行脚本推送这个可以加其他的判断逻辑实现（可能改成换的次数>0，也就是实际更换了再推送）
2.照你这样改了以后，推送会更加频繁（等于换一次就推送一次消息）

**Comment by acacia233** [comment]
应该修好了（
测试机的版本跟实际推上来的版本不一样
